export interface Country {
  name: string;
  code: string; // 3-letter ICAO code
  aliases?: string[]; // Alternative names for search
}

// Common countries list. 
export const COUNTRIES: Country[] = [
  { name: "Afghanistan", code: "AFG" },
  { name: "Albania", code: "ALB" },
  { name: "Algeria", code: "DZA" },
  { name: "Andorra", code: "AND" },
  { name: "Angola", code: "AGO" },
  { name: "Argentina", code: "ARG" },
  { name: "Armenia", code: "ARM" },
  { name: "Australia", code: "AUS" },
  { name: "Austria", code: "AUT" },
  { name: "Azerbaijan", code: "AZE" },
  { name: "Bahrain", code: "BHR" },
  { name: "Bangladesh", code: "BGD" },
  { name: "Belarus", code: "BLR" },
  { name: "Belgium", code: "BEL" },
  { name: "Bolivia", code: "BOL" },
  { name: "Bosnia and Herzegovina", code: "BIH" },
  { name: "Brazil", code: "BRA" },
  { name: "Bulgaria", code: "BGR" },
  { name: "Canada", code: "CAN" },
  { name: "Chile", code: "CHL" },
  { name: "China", code: "CHN" },
  { name: "Colombia", code: "COL" },
  { name: "Costa Rica", code: "CRI" },
  { name: "Croatia", code: "HRV" },
  { name: "Cuba", code: "CUB" },
  { name: "Cyprus", code: "CYP" },
  { name: "Czech Republic", code: "CZE" },
  { name: "Denmark", code: "DNK" },
  { name: "Egypt", code: "EGY" },
  { name: "Estonia", code: "EST" },
  { name: "Finland", code: "FIN" },
  { name: "France", code: "FRA" },
  { name: "Georgia", code: "GEO" },
  { name: "Germany", code: "D", aliases: ["Deutschland"] },
  { name: "Greece", code: "GRC" },
  { name: "Hungary", code: "HUN" },
  { name: "Iceland", code: "ISL" },
  { name: "India", code: "IND" },
  { name: "Indonesia", code: "IDN" },
  { name: "Iran", code: "IRN", aliases: ["Persia"] },
  { name: "Iraq", code: "IRQ" },
  { name: "Ireland", code: "IRL" },
  { name: "Israel", code: "ISR" },
  { name: "Italy", code: "ITA" },
  { name: "Japan", code: "JPN" },
  { name: "Jordan", code: "JOR" },
  { name: "Kazakhstan", code: "KAZ" },
  { name: "Kenya", code: "KEN" },
  { name: "Kuwait", code: "KWT" },
  { name: "Latvia", code: "LVA" },
  { name: "Lebanon", code: "LBN" },
  { name: "Lithuania", code: "LTU" },
  { name: "Luxembourg", code: "LUX" },
  { name: "Malaysia", code: "MYS" },
  { name: "Malta", code: "MLT" },
  { name: "Mexico", code: "MEX" },
  { name: "Morocco", code: "MAR" },
  { name: "Netherlands", code: "NLD", aliases: ["Holland"] },
  { name: "New Zealand", code: "NZL" },
  { name: "Nigeria", code: "NGA" },
  { name: "North Macedonia", code: "MKD" },
  { name: "Norway", code: "NOR" },
  { name: "Oman", code: "OMN" },
  { name: "Pakistan", code: "PAK" },
  { name: "Peru", code: "PER" },
  { name: "Philippines", code: "PHL" },
  { name: "Poland", code: "POL" },
  { name: "Portugal", code: "PRT" },
  { name: "Qatar", code: "QAT" },
  { name: "Romania", code: "ROU" },
  { name: "Russia", code: "RUS", aliases: ["Russian Federation"] },
  { name: "Saudi Arabia", code: "SAU" },
  { name: "Serbia", code: "SRB" },
  { name: "Singapore", code: "SGP" },
  { name: "Slovakia", code: "SVK" },
  { name: "Slovenia", code: "SVN" },
  { name: "South Africa", code: "ZAF" },
  { name: "South Korea", code: "KOR" },
  { name: "Spain", code: "ESP" },
  { name: "Sweden", code: "SWE" },
  { name: "Switzerland", code: "CHE" },
  { name: "Syria", code: "SYR" },
  { name: "Taiwan", code: "TWN" },
  { name: "Tajikistan", code: "TJK" },
  { name: "Thailand", code: "THA" },
  { name: "Turkey", code: "TUR" },
  { name: "Ukraine", code: "UKR" },
  { name: "United Arab Emirates", code: "ARE", aliases: ["UAE"] },
  { name: "United Kingdom", code: "GBR", aliases: ["UK", "Great Britain", "England"] },
  { name: "United States", code: "USA", aliases: ["US", "America", "United States of America"] },
  { name: "Utopia (Test)", code: "UTO" },
  { name: "Uzbekistan", code: "UZB" },
  { name: "Venezuela", code: "VEN" },
  { name: "Vietnam", code: "VNM" },
  { name: "Yemen", code: "YEM" }
];